---
# =========================================================
---
apiVersion: batch/v1
kind: Job
metadata:
  labels:
    app: bankinabox-preloader
  name: bankinabox-preloader
  namespace: default
spec:
  backoffLimit: 0
  template:
    metadata:
      labels:
        app: bankinabox-preloader
    spec:
      initContainers:
        - name: wait-for-database
          image: busybox
          command: ['sh', '-c', 'sleep 30']
      containers:
        - image: "gcr.io/hazelcast-33/bankinabox/preloader"
          imagePullPolicy: Always
          name: container-preloader
      restartPolicy: Never
---
