---
# =========================================================
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: pod-hazelcast-management-center
spec:
  replicas: 1
  serviceName: bankinabox-hazelcast-management-center
  selector:
    matchLabels:
      app: pod-hazelcast-management-center
  template:
    metadata:
      labels:
        app: pod-hazelcast-management-center
    spec:
      containers:
        - image: hazelcast/management-center:3.12.5
          name: container-hazelcast-management-center
---
# =========================================================
---
apiVersion: v1
kind: Service
metadata:
  name: bankinabox-hazelcast-management-center
spec:
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    app: pod-hazelcast-management-center
  type: NodePort
---
