#!/usr/bin/env bash

NAMESPACE="bankinabox"
#REGION=us-south
#REGISTRY="us.icr.io"
REGISTRY=""


for FILE in ../deploy-*.yaml
do
  echo $FILE
  cat $FILE | \
  sed 's/\$(REGISTRY)\/'"/${REGISTRY}/g" | \
  sed 's/\$(NAMESPACE)'"/${NAMESPACE}/g" | \
  sed 's/\$(IPP)'"/Never/g" | \
  kubectl apply -f -
done

oc get pods