#!/usr/bin/env bash
#
#  Copyright 2018-2021 Hazelcast, Inc
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#         http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.package com.theyawns.controller.launcher;
#

#
# pushes to docker.io/myawn/bankinabox
# access is currently restricted to Mike Yawn, I can add a few additional team
# members before exceeding the free tier limit.  Maybe each developer should have
# their own docker.io repo for this and change the registry name accordingly?
#
# It isn't clear there's an advantage to pushing to docker.io other than as a backup,
# but since everything can be easily rebuilt from GitHub even that is questionable
#

NAMESPACE="bankinabox"
REGISTRY="docker.io"   # Unused but keeping for documentation value

for BUNDLE in "grafana" "maria" "jet" "launcher" "imdg"
do
    echo $BUNDLE
#    docker tag ${NAMESPACE}/$BUNDLE:latest ${REGISTRY}/${NAMESPACE}/$BUNDLE:latest
    docker push ${NAMESPACE}/$BUNDLE:latest
done