#!/usr/bin/env bash

NAMESPACE="bankinabox"
REGISTRY=""

cat ../run-launcher.yaml | \
sed 's/\$(REGISTRY)\/'"/${REGISTRY}/g" | \
sed 's/\$(NAMESPACE)'"/${NAMESPACE}/g" | \
sed 's/\$(IPP)'"/Never/g" | \
kubectl apply -f -