#!/usr/bin/env bash

REGISTRY="gcr.io\/hazelcast-33"
NAMESPACE="bankinabox"

for FILE in ../deploy-*.yaml
do
  echo $FILE
  cat $FILE | \
  sed 's/\$(REGISTRY)'"/${REGISTRY}/g" | \
  sed 's/\$(NAMESPACE)'"/${NAMESPACE}/g" | \
  sed 's/\$(IPP)'"/Always/g" | \
  kubectl apply -f -
done
