#!/usr/bin/env bash

# This deployment assumes IMDG will be running in Hazelcast Cloud Enterprise, so the IMDG container
# does not need to be deployed.

REGISTRY="gcr.io/hazelcast-33"
NAMESPACE="bankinabox"

for FILE in ../deploy-*.yaml
do
    # Skip IMDG
  if [ $FILE == "deploy-imdg.yaml" ]
    then echo Skipping IMDG for Cloud Enterprise deployment
    continue
  fi

  echo $FILE
  cat $FILE | \
  sed 's/\$(REGISTRY)'"/${REGISTRY}/g" | \
  sed 's/\$(NAMESPACE)'"/${NAMESPACE}/g" | \
  sed 's/\$(IPP)'"/Always/g" | \
  kubectl apply -f -
done
