#!/usr/bin/env bash

REGISTRY="gcr.io\/hazelcast-33"
NAMESPACE="bankinabox"

cat ../run-launcher.yaml | \
sed 's/\$(REGISTRY)'"/${REGISTRY}/g" | \
sed 's/\$(NAMESPACE)'"/${NAMESPACE}/g" | \
sed 's/\$(IPP)'"/Always/g" | \
kubectl apply -f -