#!/usr/bin/env bash

# Leave management center, grafana, maria running so service URLs aren't impacted
# restart IMDG and JET so we start with clean data structures
# after this finishes, deployPods and startLauncher as usual

kubectl scale --replicas=0 statefulset bankinabox-imdg
kubectl scale --replicas=0 statefulset bankinabox-jet

kubectl delete horizontalpodautoscaler bankinabox-imdg

kubectl delete job bankinabox-launcher
