#!/usr/bin/env bash

# This deployment assumes IMDG will be running in Hazelcast Cloud Enterprise, so the IMDG container
# does not need to be deployed to EKS.

ECR_ACCOUNT="174325405218"
ECR_NAMESPACE="bankinabox"
ECR_REGION=us-east-1

REGISTRY="${ECR_ACCOUNT}.dkr.ecr.${ECR_REGION}.amazonaws.com"
NAMESPACE="bankinabox"

cat ../deploy-grafana.yaml | \
sed 's/\$(REGISTRY)'"/${REGISTRY}/g" | \
sed 's/\$(NAMESPACE)'"/${NAMESPACE}/g" | \
kubectl apply -f -

cat ../deploy-mariadb.yaml | \
sed 's/\$(REGISTRY)'"/${REGISTRY}/g" | \
sed 's/\$(NAMESPACE)'"/${NAMESPACE}/g" | \
kubectl apply -f -

cat ../deploy-jet.yaml | \
sed 's/\$(REGISTRY)'"/${REGISTRY}/g" | \
sed 's/\$(NAMESPACE)'"/${NAMESPACE}/g" | \
kubectl apply -f -

cat ../deploy-launcher.yaml | \
sed 's/\$(REGISTRY)'"/${REGISTRY}/g" | \
sed 's/\$(NAMESPACE)'"/${NAMESPACE}/g" | \
kubectl apply -f -

cat ../deploy-management-center.yaml | \
sed 's/\$(REGISTRY)'"/${REGISTRY}/g" | \
sed 's/\$(NAMESPACE)'"/${NAMESPACE}/g" | \
kubectl apply -f -

