#!/usr/bin/env bash
#
# For this to work, AWS CLI must be installed, and you must be able to authenticate
# against the ECR account provided in the first variable.
#

ECR_ACCOUNT="174325405218"
ECR_NAMESPACE="bankinabox"
ECR_REGION=us-east-1
ECR_REGISTRY="${ECR_ACCOUNT}.dkr.ecr.${ECR_REGION}.amazonaws.com"


aws ecr get-login-password --region ${ECR_REGION} | docker login --username AWS --password-stdin ${ECR_REGISTRY}

# What if we let maven build the images, and then just tag and push them here?
cd ../../bundle-launcher
#docker build --build-arg JAR_FILE=bundle-launcher-1.0-SNAPSHOT.jar -t bankinabox/launcher .
docker tag bankinabox/launcher:latest ${ECR_REGISTRY}/${ECR_NAMESPACE}/launcher:latest
docker push ${ECR_REGISTRY}/${ECR_NAMESPACE}/launcher:latest