#!/usr/bin/env bash
#
# For this to work, AWS CLI must be installed, and you must be able to authenticate
# against the ECR account provided in the first variable.
#
# Currently this builds images but suspect this will get pulled out,
# instead favoring let maven build the images with docker profile enabled --
# then this just needs to tag & push to ECR

ECR_ACCOUNT="174325405218"
ECR_NAMESPACE="bankinabox"
ECR_REGION=us-east-1
ECR_REGISTRY="${ECR_ACCOUNT}.dkr.ecr.${ECR_REGION}.amazonaws.com"

aws ecr get-login-password --region ${ECR_REGION} | docker login --username AWS --password-stdin ${ECR_REGISTRY}

echo Grafana
docker tag bankinabox/grafana:latest ${ECR_REGISTRY}/${ECR_NAMESPACE}/grafana:latest
docker push ${ECR_REGISTRY}/${ECR_NAMESPACE}/grafana:latest

echo MariaDB
docker tag bankinabox/maria:latest ${ECR_REGISTRY}/${ECR_NAMESPACE}/maria:latest
docker push ${ECR_REGISTRY}/${ECR_NAMESPACE}/maria:latest

echo Jet
docker tag bankinabox/jet:latest ${ECR_REGISTRY}/${ECR_NAMESPACE}/jet:latest
docker push ${ECR_REGISTRY}/${ECR_NAMESPACE}/jet:latest

echo Launcher
docker tag bankinabox/launcher:latest ${ECR_REGISTRY}/${ECR_NAMESPACE}/launcher:latest
docker push ${ECR_REGISTRY}/${ECR_NAMESPACE}/launcher:latest

# May add IMDG so we can run an all EKS config not using Cloud Enterprise, but not a priority now