#!/usr/bin/env bash
#
#  Copyright 2018-2021 Hazelcast, Inc
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#         http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.package com.theyawns.controller.launcher;
#

#
# For this to work, AWS CLI must be installed, and you must be able to authenticate
# against the ECR account provided in the first variable.
#
# Currently this builds images but suspect this will get pulled out,
# instead favoring let maven build the images with docker profile enabled --
# then this just needs to tag & push to ECR

ECR_ACCOUNT="174325405218"
ECR_NAMESPACE="bankinabox"
ECR_REGION=us-east-1
ECR_REGISTRY="${ECR_ACCOUNT}.dkr.ecr.${ECR_REGION}.amazonaws.com"

aws ecr get-login-password --region ${ECR_REGION} | docker login --username AWS --password-stdin ${ECR_REGISTRY}

for BUNDLE in "grafana" "maria" "jet" "launcher" "imdg"
do
    echo $BUNDLE
    docker tag ${ECR_NAMESPACE}/$BUNDLE:latest ${ECR_REGISTRY}/${ECR_NAMESPACE}/$BUNDLE:latest
    docker push ${ECR_REGISTRY}/${ECR_NAMESPACE}/$BUNDLE:latest
done

