#!/usr/bin/env bash

NAMESPACE="bankinabox"
REGION=us-south
REGISTRY="us.icr.io"

#ibmcloud login
#ibmcloud cr login
#ibmcloud cr region-set $REGION
#oc login

for FILE in ../deploy-*.yaml
do
  echo $FILE
  cat $FILE | \
  sed 's/\$(REGISTRY)'"/${REGISTRY}/g" | \
  sed 's/\$(NAMESPACE)'"/${NAMESPACE}/g" | \
  sed 's/\$(IPP)'"/Always/g" | \
  oc apply -f -
done

oc get pods