#!/usr/bin/env bash
#
# See https://cloud.ibm.com/kubernetes/registry/main/start?platformType=openshift

NAMESPACE="bankinabox"
REGION=us-south
REGISTRY="us.icr.io"

#ibmcloud login
#ibmcloud cr login
#ibmcloud cr region-set $REGION

for BUNDLE in "grafana" "maria" "jet" "launcher" "imdg" "management-center"
do
    echo $BUNDLE
    docker tag ${NAMESPACE}/$BUNDLE:latest ${REGISTRY}/${NAMESPACE}/$BUNDLE:latest
    docker push ${REGISTRY}/${NAMESPACE}/$BUNDLE:latest
done

ibmcloud cr image-list