#!/usr/bin/env bash
#
#  Copyright 2018-2021 Hazelcast, Inc
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#         http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.package com.theyawns.controller.launcher;
#

#
# See https://cloud.ibm.com/kubernetes/registry/main/start?platformType=openshift

NAMESPACE="bankinabox"
REGION=us-south
REGISTRY="us.icr.io"

#ibmcloud login
#ibmcloud cr login
#ibmcloud cr region-set $REGION

for BUNDLE in "grafana" "maria" "jet" "launcher" "imdg" "management-center"
do
    echo $BUNDLE
    docker tag ${NAMESPACE}/$BUNDLE:latest ${REGISTRY}/${NAMESPACE}/$BUNDLE:latest
    docker push ${REGISTRY}/${NAMESPACE}/$BUNDLE:latest
done

ibmcloud cr image-list