#!/usr/bin/env bash

#
#  Copyright 2018-2021 Hazelcast, Inc
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#         http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.package com.theyawns.controller.launcher;
#

oc scale --replicas=0 statefulset bankinabox-grafana
oc scale --replicas=0 statefulset bankinabox-imdg
oc scale --replicas=0 statefulset bankinabox-jet
oc scale --replicas=0 statefulset bankinabox-maria
#oc scale --replicas=0 statefulset bankinabox-management-center

oc delete deployment bankinabox-management-center

oc delete service bankinabox-grafana-service
oc delete service bankinabox-imdg-service
oc delete service bankinabox-jet-service
oc delete service management-center-service
oc delete service bankinabox-maria-service

oc delete horizontalpodautoscaler bankinabox-imdg

oc delete job bankinabox-launcher
